import { createClient } from "@supabase/supabase-js";
import type { ScreenPNGResult } from "./png-generator";

/**
 * ZIP Generator — Session 9
 * Creates downloadable ZIP packages with screen folders.
 * Each screen folder contains full_screen.png + individual element PNGs.
 */

function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
}

export interface ZipEntry {
  filename: string;
  content: Buffer | string;
}

/**
 * Download a file from a URL and return as Buffer.
 */
async function downloadFile(url: string): Promise<Buffer> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download file: ${response.statusText}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

/**
 * Create a ZIP file with this structure:
 * KitName_export.zip
 * ├── 01_Main_Menu/
 * │   ├── full_screen.png
 * │   ├── button_1.png
 * │   ├── heading_1.png
 * │   └── ...
 * ├── 02_HUD_In_Game_UI/
 * │   ├── full_screen.png
 * │   └── ...
 * ├── html/
 * │   ├── 01_Main_Menu.html
 * │   └── ...
 * └── design_system.json
 */
export async function createKitZip(
  kitId: string,
  kitName: string,
  pngResults: ScreenPNGResult[],
  screens: Array<{ name: string; html_css: string | null; order_index: number }>,
  designSystem: Record<string, unknown> | null
): Promise<string> {
  const archiver = await import("archiver");
  const adminSupabase = getAdminClient();

  const chunks: Buffer[] = [];

  await new Promise<void>((resolve, reject) => {
    const archive = archiver.default("zip", { zlib: { level: 6 } });

    archive.on("data", (chunk: Buffer) => chunks.push(chunk));
    archive.on("end", resolve);
    archive.on("error", reject);

    // Process each screen asynchronously then finalize
    (async () => {
      try {
        for (const pngResult of pngResults) {
          const screenIndex = screens.findIndex(
            (s) => s.name === pngResult.screenName
          );
          const orderIndex =
            screenIndex !== -1 ? screens[screenIndex].order_index : 0;
          const paddedIndex = String(orderIndex + 1).padStart(2, "0");
          const sanitizedName = pngResult.screenName.replace(
            /[^a-zA-Z0-9]/g,
            "_"
          );
          const folderName = `${paddedIndex}_${sanitizedName}`;

          // Download and add full screen PNG
          if (pngResult.fullScreenUrl) {
            try {
              const fullScreenBuffer = await downloadFile(
                pngResult.fullScreenUrl
              );
              archive.append(fullScreenBuffer, {
                name: `${folderName}/full_screen.png`,
              });
            } catch (error) {
              console.error(
                `Failed to download full screen for ${pngResult.screenName}:`,
                error
              );
            }
          }

          // Download and add element PNGs
          for (const element of pngResult.elementUrls) {
            try {
              const elementBuffer = await downloadFile(element.url);
              archive.append(elementBuffer, {
                name: `${folderName}/${element.name}.png`,
              });
            } catch {
              // Skip failed element downloads
            }
          }

          // Add HTML file
          const screen = screens.find((s) => s.name === pngResult.screenName);
          if (screen?.html_css) {
            archive.append(screen.html_css, {
              name: `html/${folderName}.html`,
            });
          }
        }

        // Add design system JSON
        if (designSystem) {
          archive.append(JSON.stringify(designSystem, null, 2), {
            name: "design_system.json",
          });
        }

        // Add README
        const readme = `# ${kitName} UI Kit
Generated by UXLora (uxlora.app)

## Contents
${pngResults
  .map((r, i) => {
    const paddedIndex = String(i + 1).padStart(2, "0");
    const sanitizedName = r.screenName.replace(/[^a-zA-Z0-9]/g, "_");
    return `- ${paddedIndex}_${sanitizedName}/
  - full_screen.png (complete screen)
  - button_*.png (individual buttons)
  - heading_*.png (headings and titles)
  - card_*.png (card components)
  - [other UI elements]`;
  })
  .join("\n")}

## HTML Files
The html/ folder contains the original HTML/CSS for each screen.
You can open these in any browser or import into Figma using the "HTML to Figma" plugin.

## Design System
design_system.json contains the complete design tokens used across all screens:
colors, typography, spacing, border radius, shadows, and component specs.
`;
        archive.append(readme, { name: "README.md" });

        archive.finalize();
      } catch (error) {
        reject(error);
      }
    })();
  });

  const zipBuffer = Buffer.concat(chunks);

  // Upload ZIP to Supabase Storage
  const sanitizedKitName = kitName.replace(/[^a-zA-Z0-9]/g, "_");
  const filePath = `kits/${kitId}/${sanitizedKitName}_export.zip`;

  const { error: uploadError } = await adminSupabase.storage
    .from("exports")
    .upload(filePath, zipBuffer, {
      contentType: "application/zip",
      upsert: true,
    });

  if (uploadError) {
    throw new Error(`ZIP upload failed: ${uploadError.message}`);
  }

  // Get signed URL (24 hour expiry)
  const { data: signedUrlData, error: signedUrlError } =
    await adminSupabase.storage
      .from("exports")
      .createSignedUrl(filePath, 60 * 60 * 24);

  if (signedUrlError || !signedUrlData) {
    throw new Error(
      `Failed to get signed URL: ${signedUrlError?.message}`
    );
  }

  return signedUrlData.signedUrl;
}

/**
 * Simple ZIP for UXML exports.
 */
export async function createUXMLZip(
  kitId: string,
  kitName: string,
  uxmlFiles: Array<{
    screenName: string;
    uxml: string;
    uss: string;
    svgCaptures?: Array<{ className: string; buffer: Buffer }>;
  }>
): Promise<string> {
  const archiver = await import("archiver");
  const adminSupabase = getAdminClient();

  const chunks: Buffer[] = [];

  await new Promise<void>((resolve, reject) => {
    const archive = archiver.default("zip", { zlib: { level: 6 } });

    archive.on("data", (chunk: Buffer) => chunks.push(chunk));
    archive.on("end", resolve);
    archive.on("error", reject);

    for (let i = 0; i < uxmlFiles.length; i++) {
      const { screenName, uxml, uss, svgCaptures } = uxmlFiles[i];
      const paddedIndex = String(i + 1).padStart(2, "0");
      const sanitizedName = screenName.replace(/[^a-zA-Z0-9]/g, "_");
      const prefix = `${paddedIndex}_${sanitizedName}`;

      archive.append(uxml, { name: `${prefix}/${prefix}.uxml` });
      archive.append(uss, { name: `${prefix}/${prefix}.uss` });

      // Add SVG captures as PNG files
      if (svgCaptures && svgCaptures.length > 0) {
        for (const capture of svgCaptures) {
          archive.append(capture.buffer, {
            name: `${prefix}/assets/${capture.className}.png`,
          });
        }
      }
    }

    // README with Unity import instructions
    archive.append(
      `# ${kitName} — Unity UXML Export
Generated by UXLora (uxlora.app)

## How to Import

1. Copy each screen folder into your Unity project under:
   Assets/UI/Screens/

2. Each folder contains:
   - [ScreenName].uxml  — The UI layout file
   - [ScreenName].uss   — The stylesheet
   - assets/            — PNG captures of SVG illustrations

3. To use SVG illustration PNGs:
   - Import the PNG files into Unity
   - In your USS, assign them using:
     background-image: url("project://database/Assets/UI/Screens/[ScreenName]/assets/[element].png");

4. Fonts:
   - Download the fonts listed in the design_system.json
   - Import into Unity as Font assets
   - Assign via: -unity-font: url("project://database/Assets/Fonts/[FontName].ttf");

## Notes
- Gradients are converted to solid colors (Unity USS limitation)
- CSS animations are removed (implement in C# scripts)
- SVG elements in assets/ folder need manual assignment in USS
- Layout structure is preserved — positions and sizes match the original design

## Support
Visit uxlora.app for documentation and support.
`,
      { name: "README.md" }
    );

    archive.finalize();
  });

  const zipBuffer = Buffer.concat(chunks);
  const sanitizedKitName = kitName.replace(/[^a-zA-Z0-9]/g, "_");
  const filePath = `kits/${kitId}/${sanitizedKitName}_uxml_export.zip`;

  const { error: uploadError } = await adminSupabase.storage
    .from("exports")
    .upload(filePath, zipBuffer, {
      contentType: "application/zip",
      upsert: true,
    });

  if (uploadError) {
    throw new Error(`UXML ZIP upload failed: ${uploadError.message}`);
  }

  const { data: signedUrlData } = await adminSupabase.storage
    .from("exports")
    .createSignedUrl(filePath, 60 * 60 * 24);

  return signedUrlData?.signedUrl ?? "";
}